sudo: false
language: node_js
node_js:
  - 12.22.1 # use nodejs v10 LTS
cache:
  npm: false
  yarn: false
branches:
  only:
    - main # build main branch only
script:
  - hexo generate # generate static files
deploy:
  provider: pages
  skip-cleanup: true
  github-token: $GH_TOKEN
  keep-history: true
  on:
    branch: main
  local-dir: public
  fqdn: blog.xiguayun.cn